site_name: cBackup
site_url: http://cbackup.me
site_description: Network equipment configuration backup software
site_author: cBackup Team

google_analytics: ['UA-102094061-1', 'cbackup.me']
repo_url: https://github.com/cbackup/main
extra_css: [assets/cbackup.css]

pages:
- Home: index.md
- Getting started:
    - Installation: getting-started/installation.md
    - Concept and terminology: getting-started/concept.md
    - Initial setup: getting-started/initial-setup.md
- System configuration: administrators-guide/system-configuration.md
- System messages: administrators-guide/system-messages.md
- User management: administrators-guide/user-management.md
- Content delivery: administrators-guide/cds.md
- Processes:
    - General info: administrators-guide/processes.md
    - Tasks: administrators-guide/tasks.md
    - Workers & jobs: administrators-guide/workers.md
- Discovery: administrators-guide/discovery.md
- Inventory:
    - Authentication: administrators-guide/authentication.md
    - Subnets: administrators-guide/subnets.md
    - Devices: administrators-guide/devices.md
    - Nodes: administrators-guide/nodes.md
- Reporting:
    - Mail: administrators-guide/mail.md
- Logs: administrators-guide/logs.md
- System update: administrators-guide/update.md
- Plugins:
    - General information: administrators-guide/plugins.md
    - Geolocation: administrators-guide/plugins/geolocation.md
- Contributors guide:
    - Translation: contributors-guide/translation.md
    - cBackup architecture: contributors-guide/architecture.md
    - Plugins: contributors-guide/plugins.md
    - Java: contributors-guide/java.md
    - API v1: contributors-guide/apiv1.md
    - API v2: contributors-guide/apiv2.md

markdown_extensions:
  - admonition
  - toc:
      permalink: True