site_name: cBackup
site_url: http://cbackup.me
site_description: Network equipment configuration backup software
site_author: cBackup Team
site_favicon: http://cbackup.me/favicon.ico

google_analytics: ['UA-102094061-1', 'cbackup.me']
repo_url: https://github.com/cbackup/main
extra_css: [assets/cbackup.css]

pages:
- Home: index.md
- Getting started:
    - Installation: getting-started/installation.md
    - Concept and terminology: getting-started/concept.md
    - Initial setup: getting-started/initial-setup.md
- Administrators guide:
    - System configuration: administrators-guide/system-configuration.md
    - System messages: administrators-guide/system-messages.md
    - User management: administrators-guide/user-management.md
    - Discovery: administrators-guide/discovery.md
    - Background service:
        - Concept: administrators-guide/concept.md
        - Global variables: administrators-guide/global-variables.md
        - Processes: administrators-guide/processes.md
        - Tasks: administrators-guide/tasks.md
        - Jobs: administrators-guide/jobs.md
        - Schedules: administrators-guide/schedules.md
    - Inventory:
        - Authentication: administrators-guide/authentication.md
        - Credentials: administrators-guide/credentials.md
        - Subnets: administrators-guide/subnets.md
        - Devices: administrators-guide/devices.md
        - Nodes: administrators-guide/nodes.md
    - Reporting:
        - Mail: administrators-guide/mail.md
    - Logs: administrators-guide/logs.md
    - System update: administrators-guide/update.md
- Developers guide:
    - cBackup architecture: developers-guide/architecture.md
    - Plugins: developers-guide/plugins.md

markdown_extensions:
  - admonition
  - toc:
      permalink: True